# Generated by Django 6.0.1 on 2026-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_alter_post_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(max_length=120, null=True, unique=True),
        ),
    ]
