# Generated by Django 6.0.1 on 2026-02-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_alter_community_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='slug',
            field=models.SlugField(default='', max_length=120, unique=True),
        ),
    ]
