# Generated by Django 6.0.1 on 2026-02-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0005_alter_community_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
    ]
